name: Publish releases to the Maven Central Repository
on:
  [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Create temp file with secrets
        run: | 
          echo "signingKey=$SIGNING_KEY" >> gradle.properties
          echo "signingPassword=$SIGNING_PASSWORD" >> gradle.properties
        env:
           SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
           SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      - name: Signing package
        run: gradle signMavenJavaPublication
        env:
           SONATYPE_USERNAME : ${{ secrets.SONATYPE_USERNAME }}
           SONATYPE_PASSWORD : ${{ secrets.SONATYPE_PASSWORD }}
